### ISSUE TITLE
Allow users to change their banner in profile page

### ISSUE THREAD

**Issue by adityachakra16** [spect-ai/app.v3#8]
**Problem**
Currently, users dont have the ability to switch their profile banners on Spect. 

![Screenshot from 2022-01-19 20-33-02](https://user-images.githubusercontent.com/31283807/150261654-78a9a531-75fb-48f9-9749-5d0bf1de197b.png)

**Solution**
As we have more designs for banners, we would like to give users the ability to change their banner images. To do this,
1. On clicking this banner, a modal should pop out where users should see their current banner and other available banners
2. They should be able to pick any one of the banner designs from the options and set it as their banner.

**Scope**

- This would only let users set existing banner designs on their profile. There is no need to let people upload their own banner designs just yet. 
- For the modal, stick to the theme and design of other modals.

**Comment by avp1598** [comment]
Gig created on spect network at https://app.spect.network/gig/226
